title: Rob | Labs
email: web@Rob|Labs.com
twitter_username: e_pi_rational
github_username:  roblabs
# global settings
title: "RobLabs.com"
description: "Creating Innovations in Maps for Print and Mobile"
url: https://roblabs.com
permalink: pretty
relative_permalinks: false

paginate: 10
paginate_path: "/blog/page:num/"

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json"]
markdown: kramdown
plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-github-metadata

sass:
  style: :compressed
