title: Rob | Labs
email: web@Rob|Labs.com
twitter_username: e_pi_rational
github_username:  roblabs
# global settings
title: "RobLabs.com"
description: "Creating Innovations in Maps for Android and iOS"
url: http://RobLabs.com
permalink: pretty
relative_permalinks: false
analytics_account: "UA-12401212-2"

paginate: 5
paginate_path: "/blog/page:num/"

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json"]
markdown: kramdown
gems:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: :compressed
