title: Rob | Labs
email: web@Rob|Labs.com
twitter_username:
github_username:  roblabs
# global settings
title: "RobLabs.com"
description: "Creating Innovations in Maps for Android and iOS"
permalink: "/stories/:title"
url: http://RobLabs.com
relative_permalinks: false
analytics_account: "UA-12401212-2"

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json"]
markdown: kramdown
gems:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap

sass:
  style: :compressed
