# Site settings
title: Rob | Labs
email: web@Rob|Labs.com
description: > # this means to ignore newlines until "baseurl:"
  …
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://RobLabs.com" # the base hostname & protocol for your site
twitter_username:
github_username:  roblabs

# Build settings
markdown: kramdown
